language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t capoen97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true capoen97/react-test npm test

after_success:
  - docker build -t capoen97/multi-client ./client
  - docker build -t capoen97/multi-nginx ./nginx
  - docker build -t capoen97/multi-server ./server
  - docker build -t capoen97/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to dockerhub
  - docker push capoen97/multi-client
  - docker push capoen97/multi-nginx
  - docker push capoen97/multi-server
  - docker push capoen97/multi-worker